### ISSUE TITLE
Value of examine searchPath field is not correct

### ISSUE THREAD

**Issue by bjarnef** [vendrhub/vendr-demo-store#10]
It seems the logic indexing value of `searchPath` field in Examine isn't correct.
https://github.com/vendrhub/vendr-demo-store/blob/main/src/Vendr.DemoStore/Composing/DemoStoreComponent.cs#L84

`e.ValueSet.Values["path"]` returns `List<object>`.

```
e.ValueSet.Add("searchPath", e.ValueSet.Values["path"].ToString().Replace(',', ' '));
```

![chrome_2020-09-08_10-54-51](https://user-images.githubusercontent.com/2919859/92456268-fd123600-f1c2-11ea-864a-dfeb04cb2a34.png)

When changing to this in seems to be correct.

```
e.ValueSet.Add("searchPath", string.Join(", ", e.ValueSet.Values["path"].Select(x => x)));
```

![chrome_2020-09-08_10-59-53](https://user-images.githubusercontent.com/2919859/92456328-12876000-f1c3-11ea-9c06-64a19de5fd97.png)

**Comment by mattbrailsford** [comment]
Good spot, however the purpose of `searchPath` is that it should be space separated, rather than comma separated as this is what makes it searchable.

Any chance you could submit a PR for this?

**Comment by bjarnef** [comment]
Ahh okay, then it would need to be this instead:

```
e.ValueSet.Add("searchPath", string.Join(" ", e.ValueSet.Values["path"].Select(x => x)));
```

**Comment by bjarnef** [comment]
Okay apparently `e.ValueSet.Values["path"] returns List<object>` and in this case only contains a single item with the path value `-1,1146,1161,1162,1163` as an object,

So it seems this works instead:

```
e.ValueSet.Add("searchPath", e.ValueSet.Values["path"][0].ToString().Replace(',', ' '));
```

![image](https://user-images.githubusercontent.com/2919859/92461740-e91e0280-f1c9-11ea-9c04-fd18e5c3ca95.png)

**Comment by bjarnef** [comment]
PR submitted: https://github.com/vendrhub/vendr-demo-store/pull/11

**Comment by mattbrailsford** [comment]
PR Merged 👍
