### ISSUE TITLE
Add gift card product

### ISSUE THREAD

**Issue by bjarnef** [vendrhub/vendr-demo-store#8]
Now with release of Vendr v.1.2 which includes gift card feature, it would be great to add a gift card product to demonstrate how to buy gift cards in Vendr. It could either be separate products with different amounts or a single product with amount in e.g. a dropdown similar to variants.

Some inspiration from various stores with gift card products:
https://shop.mikkeller.dk/products/gift-card
https://www.soundboks.com/dk/products/gift-card/

Maybe even the opportunity to add a basic message:
https://www.amazon.com/dp/B07P76HM3B/

**Comment by mattbrailsford** [comment]
We've already setup a simple example for you to test with https://try.vendr.net/products/accessories/gift-card/

**Comment by bjarnef** [comment]
Cool 👍 
Not sure if you want the different amount as well as in the links? 😁

**Comment by mattbrailsford** [comment]
Yea, possibly. Open to a PR on this one if you/anyone has the time?

**Comment by bjarnef** [comment]
Fixed in https://github.com/vendrhub/vendr-demo-store/pull/9
